# -*- coding: utf-8 -*-
"""HuggingFace_Self_Practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QfWFhhGp49agQTBAso2ZE8qD5q5U-83l
"""

!pip install -q transformers datasets torch sentencepiece sacremoses librosa soundfile accelerate

from transformers import pipeline

model = pipeline('sentiment-analysis')

example = ['I absolutely loved this movie, the acting was brilliant!',
           'This is the worst service I have ever experienced.',
           'The product is okay,nothing special but does the job']

for i in example:
  result = model(i)
  print(f'Text: {i}')
  print(f'Result: {result}\n')

from transformers import pipeline

pipe = pipeline("text-classification", model="distilbert/distilbert-base-uncased-finetuned-sst-2-english")

from transformers import AutoTokenizer, AutoModelForSequenceClassification
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased-finetuned-sst-2-english")
modelAuto = AutoModelForSequenceClassification.from_pretrained("distilbert-base-uncased-finetuned-sst-2-english")

for i in example:
  result = pipe(i)
  print(f'Text: {i}')
  print(f'Result: {result}\n')

for i in example:
  result = tokenizer.tokenize(i)
  print(f'Result: {result}\n')

example = ['I absolutely loved this movie, the acting was brilliant!',
           'This is the worst service I have ever experienced.',
           'The product is okay,nothing special but does the job']



from transformers import pipeline

pipe = pipeline("sentiment-analysis", model="mrm8488/distilroberta-finetuned-financial-news-sentiment-analysis")

#text-classification

for i in example:
  result = pipe(i)
  print(f'Text: {i}')
  print(f'Result: {result}\n')

#dslim/bert-base-NER

from transformers import AutoTokenizer, AutoModelForTokenClassification
from transformers import pipeline

tokenizer = AutoTokenizer.from_pretrained("dslim/bert-base-NER")
model = AutoModelForTokenClassification.from_pretrained("dslim/bert-base-NER",device_map='auto')

nlp = pipeline("ner", model=model, tokenizer=tokenizer)

example = ['Sundar Pichai is the CEO of Google and lives in California.',
           'Narendra modi met with the leaders in ']

import torch

for text in example:
  inputs=tokenizer(text,return_tensors='pt')
  with torch.no_grad():
    outputs=model(**inputs)



"""# Sentiment analysis"""

from transformers import pipeline

classifier = pipeline('sentiment-analysis')

classifier("Its a good weather but it could have been better")

classifier("I have been waiting for machine learning course for my whole life")

classifier("I absolutely loved this movie, the acting was brilliant")

classifier(["I absolutely loved this movie, the acting was brilliant",
            "I do not like this"])

"""#Zero shot classification"""

from transformers import pipeline

classifier2 = pipeline('zero-shot-classification')

classifier2("This is a course for Transformers library", candidate_labels=['education', 'politics', 'business'])

"""#Text Generation"""

from transformers import pipeline

classifier3 = pipeline("text-generation", model="gpt2")
classifier3("In this course we will teach you how to",max_length=100, num_return_sequences=1)

Generated_text = classifier3("In this course we will teach you how to",max_length=100, num_return_sequences=1)

print(Generated_text[0]['generated_text'])

"""## Multiple texts generated"""

from transformers import pipeline

classifier3 = pipeline("text-generation", model="gpt2")

Generated_text = classifier3("In this course we will teach you how to",max_length=50, num_return_sequences=2)

for text in Generated_text:
  print(text['generated_text'])
  print("------------------------------------------------------------------------")

"""# Fill Mask"""

from transformers import pipeline

unmasker = pipeline('fill-mask')
unmasker("This course will teach you all about <mask> models.",top_k=2 )

"""# Named Entity Recognition"""

from transformers import pipeline

ner = pipeline(model="dslim/bert-base-NER",device_map="auto")

ner_group = ner("My name is Neeraj and i work as consultant to in IT field")
for text in ner_group:
  print("word=" + text['word'] + "          " + "entity=" + text['entity'])

print(ner_group)

"""#Question Answering"""

!pip install -U transformers

from transformers import pipeline

qa = pipeline(
    "question-answering",
    model="deepset/roberta-base-squad2"
)

answer = q_a(question="where do i work?",context="My name is Neeraj and i work as consultant to in IT field",)

"""# Text to Audio"""

from transformers import pipeline

generator = pipeline(
    "text-to-audio",
    model="facebook/musicgen-small"
)

audio = generator("Happy piano music")

print(audio)

from scipy.io.wavfile import write

write(
    "relaxing_music.wav",
    rate=audio["sampling_rate"],
    data=audio["audio"]
)

"""# text-to-speech"""

from transformers import pipeline

generator = pipeline(
    "text-to-speech",
    #model="suno/bark-small"
    #model="microsoft/speecht5_tts"
    model="facebook/mms-tts-eng"
)

speech = generator("my name is N eeraj....    My daughter name is Nirvi.....     Deepali is my life...   Thank you")

print(speech)

from scipy.io.wavfile import write

write(
    "text_to_speech_3.wav",
    rate=speech["sampling_rate"],
    data=speech["audio"]
)

"""## Translation,  Summarization"""

